# This is just a file for me to test bits of code

In [1]:
import numpy as np

state = np.array([[1, 2, 0], [1, 1, 0], [1, 0, 100]])
state2 = np.array([[1, 2, 0], [1, 1, 0], [1, 0, 100]]) * 2

print(state, state2)

[[  1   2   0]
 [  1   1   0]
 [  1   0 100]] [[  2   4   0]
 [  2   2   0]
 [  2   0 200]]


In [7]:
print(state)

[[  1   2   0]
 [  1   1   0]
 [  1   0 100]]


In [8]:
print(state / np.linalg.norm(state, axis=1))

[[0.4472136  1.41421356 0.        ]
 [0.4472136  0.70710678 0.        ]
 [0.4472136  0.         0.99995   ]]


In [2]:
state - state2

array([[  -1,   -2,    0],
       [  -1,   -1,    0],
       [  -1,    0, -100]])