# This is just a file for me to test bits of code

In [9]:
import numpy as np

state = np.array([[1, 2, 0], [1, 1, 0], [1, 0, 100]])
state2 = np.array([[1, 2, 0], [1, 1, 0], [1, 0, 100]]) * 2

print(state, state2)

[[  1   2   0]
 [  1   1   0]
 [  1   0 100]] [[  2   4   0]
 [  2   2   0]
 [  2   0 200]]


In [12]:
print(np.sum(np.linalg.norm(state, axis = 1)))

103.65528141487913
