# In this file I attempt to build the basic framework for doing numerics on the Hyzenberg Spin Chain (without refrence to my professors work)
- Im doing feromagnet bc its cooler

# Imports

In [60]:
import numpy as np

# General variables

In [61]:
L = 120 # number of spins 
#(note: if you are going to be working with a spiral with periodic boundy condtions, make sure L is st the spiral is maintained through the Lth --> 0th spin)

J = 1 # energy factor

J_vec = J * np.array([np.random.choice([-1, 1]), np.random.choice([-1, 1]), 1])

# Defining the initial state

In [62]:
# Making a state wherein the initial spins are all in random directions
def make_random_state(n=L):
    state = [] # states are numpy arrays of 3D vecotors (numpy arrays)
    for i in range(n):
        spin_i = np.random.rand(3)
        state.append(spin_i / np.linalg.norm(spin_i))
    
    return np.array(state)

# Making a state wherin all the spins are along a certain z _dir
def make_uniform_state(n=L, z_dir=1):
    state = [] # states are numpy arrays of 3D vecotors (numpy arrays)
    for i in range(n):
        spin_i = [0, 0, z_dir]
        state.append(spin_i)
    
    return np.array(state)

# Make a state wherin the spins look like they are tumbling over each other 
# (most likley the pi/4 spiral will be most used becuase we know it to be an unstable stationary state)
def make_spiral_state(n=L, spiral_angle=np.pi/4, phi=0):
    state = [] # states are numpy arrays of 3D vecotors (numpy arrays)
    for i in range(n):
        spin_i = [0, np.cos(i * spiral_angle + phi), np.sin(i * spiral_angle + phi)]
        state.append(spin_i)
    
    return np.array(state)

# The equation of motion

In [63]:
def diffrential_s(state):
    dstate_dt = []
    for i in range(len(state)):
        prev_index = i-1
        next_index = (i+1) % len(state) # This is assuming we are considering everything to be periodic
        dstate_dt.append(np.cross(-(J * state[prev_index] + J * state[next_index]), state[i]))

    return dstate_dt

In [64]:
## Testing diffrential_s for pi/4 spin state
s_naught = make_spiral_state(L)

print(diffrential_s(s_naught))

# Defining s_naught as a constant
S_NAUGHT = make_spiral_state(L)

[array([-5.77315973e-15,  0.00000000e+00,  0.00000000e+00]), array([1.11022302e-16, 0.00000000e+00, 0.00000000e+00]), array([-2.44266968e-17,  0.00000000e+00,  0.00000000e+00]), array([-1.11022302e-16,  0.00000000e+00,  0.00000000e+00]), array([6.21689088e-17, 0.00000000e+00, 0.00000000e+00]), array([0., 0., 0.]), array([3.77422119e-17, 0.00000000e+00, 0.00000000e+00]), array([0., 0., 0.]), array([1.33155151e-17, 0.00000000e+00, 0.00000000e+00]), array([1.11022302e-16, 0.00000000e+00, 0.00000000e+00]), array([-5.66222694e-16,  0.00000000e+00,  0.00000000e+00]), array([1.11022302e-15, 0.00000000e+00, 0.00000000e+00]), array([7.54844239e-17, 0.00000000e+00, 0.00000000e+00]), array([-1.22124533e-15,  0.00000000e+00,  0.00000000e+00]), array([-5.99645754e-17,  0.00000000e+00,  0.00000000e+00]), array([1.22124533e-15, 0.00000000e+00, 0.00000000e+00]), array([2.66310302e-17, 0.00000000e+00, 0.00000000e+00]), array([-1.22124533e-15,  0.00000000e+00,  0.00000000e+00]), array([2.20433337e-18, 0

# The push to s_naught

In [67]:
def control_push(spin, a):
    numerator = ((1-a) * S_NAUGHT) + (a*spin) # pushes S_j to S_NAUGHT
    denominator = np.linalg.norm(((1-a) * S_NAUGHT) + (a*spin), axis=1, keepdims=True) # Keeps magnitude of S_j = 1
    return numerator / denominator

## Testing push

In [68]:
test_spin = make_random_state(L)

print(test_spin[0], np.linalg.norm(test_spin[0]))
controled_test = control_push(test_spin, 1)
print(controled_test[0], np.linalg.norm(controled_test[0]))

[0.53145857 0.7897452  0.30635649] 0.9999999999999999
[0.53145857 0.7897452  0.30635649] 1.0000000000000002


In [58]:
print(test_spin - controled_test)

[[0.18119749 0.86354776 0.21728295]
 [0.60306858 0.53413632 0.42043528]
 [0.65373802 0.57636211 0.25727896]
 [0.01375404 0.8357994  0.3563837 ]
 [0.19267293 0.61794693 0.63779141]
 [0.75985686 0.19072317 0.46043606]
 [0.34358778 0.49101849 0.68308669]
 [0.85452537 0.04501174 0.30580955]
 [0.45342359 0.56398658 0.5496229 ]
 [0.02854313 0.4161901  0.80729811]
 [0.08996581 0.64725951 0.63144313]
 [0.16015007 0.88488499 0.13072742]
 [0.79305305 0.33587602 0.2898505 ]
 [0.22293837 0.15284413 0.86758072]
 [0.4894365  0.42066775 0.63972627]
 [0.87764032 0.12428003 0.20015266]
 [0.77360646 0.44083984 0.18152805]
 [0.37482082 0.2700025  0.78253892]
 [0.51979948 0.47166616 0.57714702]
 [0.06404096 0.88867477 0.17864784]
 [0.42687918 0.54527749 0.58839254]
 [0.76865496 0.03618682 0.48334171]
 [0.06341076 0.81392709 0.39907507]
 [0.53308872 0.72119465 0.14647129]
 [0.61824162 0.13708199 0.65172462]
 [0.38994698 0.3867834  0.72394689]
 [0.52421149 0.7119056  0.2101235 ]
 [0.14267337 0.60740027 0.66

In [57]:
print(S_NAUGHT - controled_test)

[[-1.82026598e-02  9.13250088e-01 -2.18277174e-02]
 [-6.05828062e-02  6.53448743e-01  6.64870874e-01]
 [-6.56729346e-02 -5.78999390e-02  9.74154380e-01]
 [-1.38169717e-03 -7.91069160e-01  6.71305340e-01]
 [-1.93554551e-02 -1.06207745e+00 -6.40709770e-02]
 [-7.63333761e-02 -7.26266368e-01 -7.53361070e-01]
 [-3.45159941e-02 -4.93265257e-02 -1.06862123e+00]
 [-8.58435447e-02  7.02585011e-01 -7.37827666e-01]
 [-4.55498335e-02  9.43343277e-01 -5.52137824e-02]
 [-2.86737381e-03  6.65297334e-01  6.26007572e-01]
 [-9.03774713e-03 -6.50221191e-02  9.36566756e-01]
 [-1.60882869e-02 -7.96000179e-01  6.93974222e-01]
 [-7.96681842e-02 -1.03374129e+00 -2.91176772e-02]
 [-2.23958471e-02 -7.22461132e-01 -7.94261834e-01]
 [-4.91676032e-02 -4.22592613e-02 -1.06426535e+00]
 [-8.81656164e-02  6.94621911e-01 -7.27213631e-01]
 [-7.77146272e-02  9.55714300e-01 -1.82358668e-02]
 [-3.76535893e-02  6.79982986e-01  6.28494821e-01]
 [-5.22177940e-02 -4.73824376e-02  9.42021211e-01]
 [-6.43339973e-03 -7.96380892e-